[global]
target = "~/.local/bin"
quiet = false
#upgrade_only = true

["zyedidia/eget"]

["twpayne/chezmoi"]
asset_filters = [ "linux_amd64", ".tar.gz" ]
file = "chezmoi"

["mkropat/jumpapp"]
asset_filters = [ ".tar.bz2" ]
file = "jumpapp"

["alex2108/syncthing-tray"]

["doy/rbw"]
file = "rbw*"
all = true

["containerd/nerdctl"]
asset_filters = [ "nerdctl-1", "linux-amd64" ]
all = true

["rgwood/systemctl-tui"]

["joehillen/sysz"]

["shadowsocks/shadowsocks-rust"]
asset_filters = [ "linux-gnu" ]
file = "sslocal"

["imsnif/bandwhich"]
asset_filters = [ "linux-gnu" ]

["extremecoders-re/go-dispatch-proxy"]

["telegramdesktop/tdesktop"]
asset_filters = [ ".tar.xz" ]
all = true

["v2fly/v2ray-core"]
asset_filters = [ "linux-64.zip", "^dgst" ]
file = "v2ray"

["lostdusty/cobalt"]
asset_filters = [ "cobalt-linux-amd64.tar.gz" ]
target = "~/.local/bin/cobalt"