#!/usr/bin/env bash

# https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/
#echo 'use scripts!'
#pip install --user --break-system-packages rofi-rbw
#curl https://zyedidia.github.io/eget.sh | sh
#eget -D

