# -*- mode: Shell-script; sh_shell: "bash"; -*-

# run functions
create_local_dirs
add_opt_liquidprompt
add_opt_fzf zsh

# Load all stock functions (from $fpath files) called below.
autoload -Uz compaudit compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# highlight completion
zstyle ':completion:*' menu select

if [ -z "$ZSH_COMPDUMP" ]; then
  ZSH_COMPDUMP="${ZDOTDIR:-${HOME}}/.zcompdump-${SHORT_HOST}-${ZSH_VERSION}"
fi

# history
setopt sharehistory \
       hist_ignore_space \
       hist_ignore_all_dups \
       hist_ignore_dups \
       hist_ignore_space \
       hist_reduce_blanks \
       hist_save_no_dups \
       hist_verify
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# get bash complete to work in zsh
#[[ -n "$ZSH_VERSION" ]] && autoload bashcompinit && bashcompinit
