;;; https://www.gnu.org/software/emacs/manual/html_node/elisp/Window-Frame-Parameters.html
(setq default-frame-alist
      '(
;	(left . 1.0)
        (top . -1)
	(user-position . t)
	(height . 0.5)
        (width . 1.0)
	(user-size . t)
;	(fullscreen . maximized)
;	(fullscreen . fullheight)
	(vertical-scroll-bars . nil)
        (horizontal-scroll-bars . nil)
	(menu-bar-lines . 0)
        (tool-bar-lines . 0)
	(wait-for-wm . t)
	(cursor-type . box)
;	(font . "Vazir Code Hack")
	(font . "-    -Vazir Code Hack Extra Height-regular-normal-normal-*-17-*-*-*-m-0-iso10646-1")
       )
)
