export VISUAL=micro
export EDITOR=micro

# # If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# oh love
shopt -s autocd

# correct typos
shopt -s cdspell

# run functions
source_completion
create_local_dirs

#echo $- | grep -q i 2>/dev/null && . /usr/share/liquidprompt/liquidprompt

PS1=$PS1'\[$(vterm_prompt_end)\]'